version: '3'

services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /tmp/mongo:/data/db
    networks:
      - net-example

  docker-example:
    image: docker-example
    ports:
      - '8080:8080'
    volumes:
      - /tmp:/tmp
    networks:
      - net-example
    depends_on:
      - 'mongo-db'

networks:
  net-example: